#!/usr/bin/env python3
import sys

sys.path.append(".")

from lifeguard import setup
from lifeguard.context import LIFEGUARD_CONTEXT
from lifeguard.scheduler import start_scheduler

setup(LIFEGUARD_CONTEXT)
start_scheduler()
